version: "3"
#################################################################
##
## THIS FILE CONTAINS THE ENTRIES FOR THE INFRASTRUCTURE
# To create the network you run the following:
## docker network create net --gateway 192.168.0.1 --subnet 192.168.0.1/24
##    ALSO: --gateway --ip-range and --aux-address can be used
# https://docs.docker.com/engine/reference/commandline/network_create/
#################################################################
services:
#################################################################
##  Parrotsec/ParOS
#################################################################
    parrot:
      image: parrotsec/security
      volumes:
        - "/run/docker.sock:/var/run/docker.sock"
        -  /tmp/msf:/tmp/data:Z
      networks:
        net:
          ipv4_address: ${PARROTOSIP}
      network_mode: host
