apiVersion: v1
kind: Service
metadata:
  labels:
    app: placeholder
  name: placeholder
spec:
  loadBalancerIP: 192.168.0.1
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: placeholder
  type: LoadBalancer
